### PR TITLE
Require jdk11 and upgrade to gradle 5.2.1

### PR DESCRIPTION
**Pull request by andreidan**

### CODE REVIEW

**Comment by andreidan** [comment]
retest this please

**Comment by andreidan** [comment]
> Could we follow up on this with a change to `testQueryStatsMetrics` so that we see what values are wrong?
> 
> The
> 
> ```
> io.crate.jmx.integrationtests.MetricsITest > testQueryStatsMetrics FAILED
>     java.lang.AssertionError at MetricsITest.java:128
> ```
> 
> isn't very helpful

Yeah, I find it strange it doesn't already as the assertion has a reason. I suspect this failure is to do with the agent not picking up the "proper" latest on a first run

**Comment by andreidan** [comment]
retest this please

**Comment by andreidan** [comment]
retest this please

**Comment by andreidan** [comment]
retest this please

**Comment by andreidan** [comment]
retest this please

**Comment by andreidan** [comment]
retest this please

**Comment by andreidan** [comment]
retest this please

**Comment by andreidan** [comment]
retest this please

**Comment by mfussenegger** [comment]
retest this please

**Pull request merged**
