### PR TITLE
Prepare release 0.6.0

### PR DESCRIPTION
**Pull request by andreidan**

### CODE REVIEW

**Comment by chaudum** [comment]
Would it make sense to also update the version in the example configuration in the README?

**Comment by seut** [comment]
@andreidan tests are failing

**Comment by seut** [comment]
> Would it make sense to also update the version in the example configuration in the README?

We should do this as a followup task of every release, also pointing to the new release download at the README.

@andreidan Seems this wasn't done for the 0.5.0 release, although it is documented as a release step at the DEVELOP.rst. Should we improve the documentation?

**Comment by andreidan** [comment]
retest this please

**Comment by andreidan** [comment]
@chaudum  thanks for pointing it out. I missed it completely.

@seut I just missed it, I don't think we need to change anything

**Comment by andreidan** [comment]
retest this please

**Comment by andreidan** [comment]
retest this please

**Comment by andreidan** [comment]
@seut tests are passing

**Comment by mfussenegger** [comment]
> I just missed it, I don't think we need to change anything

We could add a comment above https://github.com/crate/jmx_exporter/pull/40/files#diff-c197962302397baf3a4cc36463dce5eaR19 that says please update the readme, so that it is harder to miss.

**Pull request merged**
